"""add match and match_stats tables

Revision ID: 02c9a443ecf8
Revises: 117d1fc4bc85
Create Date: 2026-08-08 21:13:50.915940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02c9a443ecf8'
down_revision: Union[str, Sequence[str], None] = '117d1fc4bc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league', 'date', 'home_team', 'away_team', name='uq_match_league_date_teams')
    )
    op.create_index(op.f('ix_match_date'), 'match', ['date'], unique=False)
    op.create_index(op.f('ix_match_league'), 'match', ['league'], unique=False)
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_stats_match_id'), 'match_stats', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_stats_match_id'), table_name='match_stats')
    op.drop_table('match_stats')
    op.drop_index(op.f('ix_match_league'), table_name='match')
    op.drop_index(op.f('ix_match_date'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
