"""add model_artifact table

Revision ID: 117d1fc4bc85
Revises: 0e52855ab174
Create Date: 2026-08-08 19:32:54.634666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '117d1fc4bc85'
down_revision: Union[str, Sequence[str], None] = '0e52855ab174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelartifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trained_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_up_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelartifact_league'), 'modelartifact', ['league'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelartifact_league'), table_name='modelartifact')
    op.drop_table('modelartifact')
    # ### end Alembic commands ###
