"""phase14 referral promoter platform

Revision ID: 5787c4b3b963
Revises: c4f8a1d75e93
Create Date: 2026-08-31 23:18:29.963545

Phase 14 : programme de promotion/affiliation — DDL auto-générée (non
modifiée à la main, même discipline que la migration ecf43e1d3a33), 5
nouvelles tables STRICTEMENT ADDITIVES (promoter, referral_attribution,
referral_commission, referral_visit, referral_audit_event) — voir
app/models/promoter.py pour la justification de chaque table/contrainte.

Aucune table existante n'est touchée : ni les tables IA (match/match_stats/
model_predictions/model_versions/prediction_log/team_ratings, §41/§48 du
prompt Phase 14), ni user/provider_subscription/entitlement (référencées
uniquement via ForeignKeyConstraint en lecture, jamais modifiées).

downgrade() ne supprime que ces 5 tables — aucune donnée pré-existante n'est
jamais en danger, dans un sens comme dans l'autre.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5787c4b3b963'
down_revision: Union[str, Sequence[str], None] = 'c4f8a1d75e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commission_rate_bp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promoter_slug'), 'promoter', ['slug'], unique=True)
    op.create_index(op.f('ix_promoter_user_id'), 'promoter', ['user_id'], unique=True)
    op.create_table('referral_attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('converted_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributed_at', sa.DateTime(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('converted_user_id', name='uq_referral_attribution_converted_user')
    )
    op.create_index(op.f('ix_referral_attribution_converted_user_id'), 'referral_attribution', ['converted_user_id'], unique=False)
    op.create_index(op.f('ix_referral_attribution_promoter_id'), 'referral_attribution', ['promoter_id'], unique=False)
    op.create_index(op.f('ix_referral_attribution_visitor_id'), 'referral_attribution', ['visitor_id'], unique=False)
    op.create_table('referral_audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_audit_event_promoter_id'), 'referral_audit_event', ['promoter_id'], unique=False)
    op.create_table('referral_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gross_paid_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commission_rate_bp', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.ForeignKeyConstraint(['provider_subscription_id'], ['provider_subscription.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', name='uq_referral_commission_source_event')
    )
    op.create_index(op.f('ix_referral_commission_promoter_id'), 'referral_commission', ['promoter_id'], unique=False)
    op.create_index(op.f('ix_referral_commission_provider_subscription_id'), 'referral_commission', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_referral_commission_referred_user_id'), 'referral_commission', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referral_commission_source_event_id'), 'referral_commission', ['source_event_id'], unique=False)
    op.create_table('referral_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_visit_promoter_id'), 'referral_visit', ['promoter_id'], unique=False)
    op.create_index(op.f('ix_referral_visit_visitor_id'), 'referral_visit', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_visit_visitor_id'), table_name='referral_visit')
    op.drop_index(op.f('ix_referral_visit_promoter_id'), table_name='referral_visit')
    op.drop_table('referral_visit')
    op.drop_index(op.f('ix_referral_commission_source_event_id'), table_name='referral_commission')
    op.drop_index(op.f('ix_referral_commission_referred_user_id'), table_name='referral_commission')
    op.drop_index(op.f('ix_referral_commission_provider_subscription_id'), table_name='referral_commission')
    op.drop_index(op.f('ix_referral_commission_promoter_id'), table_name='referral_commission')
    op.drop_table('referral_commission')
    op.drop_index(op.f('ix_referral_audit_event_promoter_id'), table_name='referral_audit_event')
    op.drop_table('referral_audit_event')
    op.drop_index(op.f('ix_referral_attribution_visitor_id'), table_name='referral_attribution')
    op.drop_index(op.f('ix_referral_attribution_promoter_id'), table_name='referral_attribution')
    op.drop_index(op.f('ix_referral_attribution_converted_user_id'), table_name='referral_attribution')
    op.drop_table('referral_attribution')
    op.drop_index(op.f('ix_promoter_user_id'), table_name='promoter')
    op.drop_index(op.f('ix_promoter_slug'), table_name='promoter')
    op.drop_table('promoter')
    # ### end Alembic commands ###
