"""phase15_14 promoter withdrawal

Revision ID: 99fd1d8ad121
Revises: 5787c4b3b963
Create Date: 2026-09-03 22:10:35.946881

Phase 15.14 : retrait MANUEL des commissions promoteurs — DDL auto-générée
(non modifiée à la main, même discipline que 5787c4b3b963), UNE seule
nouvelle table STRICTEMENT ADDITIVE (promoter_withdrawal) — voir
app/models/promoter.py::PromoterWithdrawal pour la justification de chaque
colonne/contrainte.

Aucune table existante n'est touchée : ni les tables IA (match/match_stats/
model_predictions/model_versions/prediction_log/team_ratings), ni
user/promoter/referral_commission (référencées uniquement en lecture via
ForeignKeyConstraint, jamais modifiées).

L'index UNIQUE PARTIEL 'uq_promoter_withdrawal_one_pending' (WHERE status =
'PENDING') est fonctionnellement identique sous SQLite et PostgreSQL — les
deux moteurs réellement utilisés par ce projet (voir app/core/database.py).

downgrade() ne supprime que cette table — aucune donnée pré-existante n'est
jamais en danger, dans un sens comme dans l'autre.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99fd1d8ad121'
down_revision: Union[str, Sequence[str], None] = '5787c4b3b963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoter_withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promoter_withdrawal_promoter_id'), 'promoter_withdrawal', ['promoter_id'], unique=False)
    op.create_index(op.f('ix_promoter_withdrawal_status'), 'promoter_withdrawal', ['status'], unique=False)
    op.create_index('uq_promoter_withdrawal_one_pending', 'promoter_withdrawal', ['promoter_id'], unique=True, sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_promoter_withdrawal_one_pending', table_name='promoter_withdrawal', sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_promoter_withdrawal_status'), table_name='promoter_withdrawal')
    op.drop_index(op.f('ix_promoter_withdrawal_promoter_id'), table_name='promoter_withdrawal')
    op.drop_table('promoter_withdrawal')
    # ### end Alembic commands ###
