"""add team_ratings and model_versions tables

Revision ID: ab1e08d0a3ca
Revises: 02c9a443ecf8
Create Date: 2026-08-09 19:31:50.374701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab1e08d0a3ca'
down_revision: Union[str, Sequence[str], None] = '02c9a443ecf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_type'), 'model_versions', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=True)
    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attack', sa.Float(), nullable=False),
    sa.Column('defense', sa.Float(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team', 'league', 'model_version_id', name='uq_team_ratings_team_league_model_version')
    )
    op.create_index(op.f('ix_team_ratings_league'), 'team_ratings', ['league'], unique=False)
    op.create_index(op.f('ix_team_ratings_model_version_id'), 'team_ratings', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_team_ratings_team'), 'team_ratings', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_ratings_team'), table_name='team_ratings')
    op.drop_index(op.f('ix_team_ratings_model_version_id'), table_name='team_ratings')
    op.drop_index(op.f('ix_team_ratings_league'), table_name='team_ratings')
    op.drop_table('team_ratings')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_type'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
