"""add provider_subscription entitlement entitlement_event

Revision ID: ecf43e1d3a33
Revises: f1a2b3c4d5e6
Create Date: 2026-08-26 21:56:32.135444

Phase 1 de la migration Chariow -> architecture Provider/Entitlement (voir
document d'architecture "Coexistence Chariow + Google Play"). Crée les 3
nouvelles tables (DDL auto-générée, non modifiée à la main) PUIS backfill
Subscription -> ProviderSubscription -> Entitlement via
app/billing/backfill.py — jamais de logique dupliquée entre cette migration
et le fonctionnement normal de l'application.

NE TOUCHE JAMAIS à `subscription`/`processedpulsedelivery` (ni lecture
destructive, ni écriture, ni suppression) — coupure nette validée pour
cette phase : aucune double-écriture, l'ancienne table reste un instantané
figé de l'état pré-migration, jamais plus modifiée après ce backfill.

downgrade() ne supprime que les 3 nouvelles tables : la donnée Chariow
historique n'est donc jamais en danger, dans un sens comme dans l'autre.

IMPORTANT : prévue pour tourner sur SQLite en local (voir consignes de
cette phase — rien n'est appliqué sur Railway/production ici). Le backfill
fait un commit par utilisateur (via recompute_entitlement) ; sur PostgreSQL
ceci interagirait avec la transaction gérée par Alembic — à revoir avant
toute exécution en production (voir app/billing/backfill.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import Session


# revision identifiers, used by Alembic.
revision: str = 'ecf43e1d3a33'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlement',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.Column('premium_until', sa.DateTime(), nullable=True),
    sa.Column('active_sources', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('provider_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('days_until_expiry', sa.Integer(), nullable=True),
    sa.Column('auto_renewing', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_or_refunded_at', sa.DateTime(), nullable=True),
    sa.Column('raw_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_ref', name='uq_provider_subscription_provider_external_ref'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_provider_subscription_user_provider')
    )
    op.create_index(op.f('ix_provider_subscription_external_ref'), 'provider_subscription', ['external_ref'], unique=False)
    op.create_index(op.f('ix_provider_subscription_provider'), 'provider_subscription', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_subscription_user_id'), 'provider_subscription', ['user_id'], unique=False)
    op.create_table('entitlement_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_subscription_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_premium', sa.Boolean(), nullable=False),
    sa.Column('new_premium', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_subscription_id'], ['provider_subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlement_event_user_id'), 'entitlement_event', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Backfill Chariow : Subscription -> ProviderSubscription -> Entitlement ---
    # Import différé (pas en haut du fichier) : app/billing/backfill.py importe
    # des modèles SQLModel, à ne charger qu'une fois les tables ci-dessus créées.
    from app.billing.backfill import backfill_provider_subscriptions, backfill_entitlements

    bind = op.get_bind()
    with Session(bind=bind) as session:
        n_provider_subs = backfill_provider_subscriptions(session)
        n_entitlements = backfill_entitlements(session)
    print(f"[backfill] {n_provider_subs} ProviderSubscription créées, {n_entitlements} Entitlement calculés.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitlement_event_user_id'), table_name='entitlement_event')
    op.drop_table('entitlement_event')
    op.drop_index(op.f('ix_provider_subscription_user_id'), table_name='provider_subscription')
    op.drop_index(op.f('ix_provider_subscription_provider'), table_name='provider_subscription')
    op.drop_index(op.f('ix_provider_subscription_external_ref'), table_name='provider_subscription')
    op.drop_table('provider_subscription')
    op.drop_table('entitlement')
    # ### end Alembic commands ###
