"""add google_play_purchase processed_google_notification

Revision ID: f34a28d2538d
Revises: ecf43e1d3a33
Create Date: 2026-08-26 22:22:56.217942

Phase 2 (Google Play backend). Aucune donnée historique à migrer (aucun
achat Google n'existe encore) — DDL pure, pas de backfill. NE TOUCHE À
AUCUNE table existante (subscription, provider_subscription, entitlement,
entitlement_event) : aucune colonne ajoutée/modifiée/supprimée dessus.

downgrade() supprime uniquement les 2 nouvelles tables — réversible sans
aucun risque sur les données Chariow/Entitlement Phase 1.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f34a28d2538d'
down_revision: Union[str, Sequence[str], None] = 'ecf43e1d3a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_google_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubsub_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_google_notification_pubsub_message_id'), 'processed_google_notification', ['pubsub_message_id'], unique=True)
    op.create_table('google_play_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acknowledgement_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('auto_renewing', sa.Boolean(), nullable=False),
    sa.Column('linked_purchase_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_or_refunded_at', sa.DateTime(), nullable=True),
    sa.Column('latest_notification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_subscription_id'], ['provider_subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_play_purchase_provider_subscription_id'), 'google_play_purchase', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_google_play_purchase_purchase_token'), 'google_play_purchase', ['purchase_token'], unique=True)
    op.create_index(op.f('ix_google_play_purchase_user_id'), 'google_play_purchase', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_play_purchase_user_id'), table_name='google_play_purchase')
    op.drop_index(op.f('ix_google_play_purchase_purchase_token'), table_name='google_play_purchase')
    op.drop_index(op.f('ix_google_play_purchase_provider_subscription_id'), table_name='google_play_purchase')
    op.drop_table('google_play_purchase')
    op.drop_index(op.f('ix_processed_google_notification_pubsub_message_id'), table_name='processed_google_notification')
    op.drop_table('processed_google_notification')
    # ### end Alembic commands ###
